export const elements = {
  bestiary: [
    {
      id: 1,
      title: "Virus Soldier",
      isEnemy: true,
      locationText:
        "Found in Intro Stage/Central Station, Cable/Power Circuit, Hash/Cipher Circuit, Crash/Break Circuit, Ark Stage 3/Depths",
      locations: [
        "Intro Stage/Central Station",
        "Cable/Power Circuit",
        "Hash/Cipher Circuit",
        "Crash/Break Circuit",
        "Ark Stage 3/Depths",
      ],
    },
    {
      id: 2,
      title: "Shielded Soldier",
      isEnemy: true,
      locationText: "Found in All Stages",
      locations: ["All Stages"],
    },
    {
      id: 3,
      title: "Virus Engineer",
      isEnemy: true,
      locationText:
        "Found in Intro Stage/Central Station, Cable/Power Circuit, Ark Stage 2/Machinery, Ark Stage 3/Depths",
      locations: [
        "Intro Stage/Central Station",
        "Cable/Power Circuit",
        "Ark Stage 2/Machinery",
        "Ark Stage 3/Depths",
      ],
    },
    {
      id: 4,
      title: "Virus Wrecker",
      isEnemy: true,
      locationText:
        "Found in Intro Stage/Central Station, Crash/Break Circuit, Ark Stage 1/Entrance, Ark Stage 3/Depths",
      locations: [
        "Intro Stage/Central Station",
        "Crash/Break Circuit",
        "Ark Stage 1/Entrance",
        "Ark Stage 3/Depths",
      ],
    },
    {
      id: 5,
      title: "Virus Cannoneer",
      isEnemy: true,
      locationText:
        "Found in Hash/Cipher Circuit, Bit/Shift Circuit, Ark Stage 1/Entrance, Ark Stage 3/Depths",
      locations: [
        "Hash/Cipher Circuit",
        "Bit/Shift Circuit",
        "Ark Stage 1/Entrance",
        "Ark Stage 3/Depths",
      ],
    },
    {
      id: 6,
      title: "Spikey",
      isEnemy: true,
      locationText:
        "Found in Intro Stage/Central Station, Cable/Power Circuit, Hash/Cipher Circuit, Crash/Break Circuit, Bit/Shift Circuit, Ark Stage 1/Entrance, Ark Stage 2/Machinery, Ark Stage 3/Depths",
      locations: [
        "Intro Stage/Central Station",
        "Cable/Power Circuit",
        "Hash/Cipher Circuit",
        "Crash/Break Circuit",
        "Bit/Shift Circuit",
        "Ark Stage 1/Entrance",
        "Ark Stage 2/Machinery",
        "Ark Stage 3/Depths",
      ],
    },
    {
      id: 7,
      title: "Cyber Spikey",
      isEnemy: true,
      locationText: "Found in Hash/Cipher Circuit",
      locations: ["Hash/Cipher Circuit"],
    },
    {
      id: 8,
      title: "Fire Spitter",
      isEnemy: true,
      locationText: "Found in Ray/Optic Circuit, Ark Stage 2/Machinery",
      locations: ["Ray/Optic Circuit", "Ark Stage 2/Machinery"],
    },
    {
      id: 9,
      title: "Lava Crawler",
      isEnemy: true,
      locationText: "Found in Ray/Optic Circuit, Ark Stage 2/Machinery",
      locations: ["Ray/Optic Circuit", "Ark Stage 2/Machinery"],
    },
    {
      id: 10,
      title: "Junk Fly",
      isEnemy: true,
      locationText: "Found in Trace/Patch Circuit, Ark Stage 3/Depths",
      locations: ["Trace/Patch Circuit", "Ark Stage 3/Depths"],
    },
    {
      id: 11,
      title: "Junk Fly Hive",
      isEnemy: true,
      locationText: "Found in Trace/Patch Circuit, Ark Stage 3/Depths",
      locations: ["Trace/Patch Circuit", "Ark Stage 3/Depths"],
    },
    {
      id: 12,
      title: "Virus Zombie",
      isEnemy: true,
      locationText: "Found in Trace/Patch Circuit, Ark Stage 3/Depths",
      locations: ["Trace/Patch Circuit", "Ark Stage 3/Depths"],
    },
    {
      id: 13,
      title: "Turret Zombie",
      isEnemy: true,
      locationText: "Found in Trace/Patch Circuit, Ark Stage 3/Depths",
      locations: ["Trace/Patch Circuit", "Ark Stage 3/Depths"],
    },
    {
      id: 14,
      title: "Battie",
      isEnemy: true,
      locationText:
        "Found in Crash/Break Circuit, Trace/Patch Circuit, Ark Stage 3/Depths",
      locations: [
        "Crash/Break Circuit",
        "Trace/Patch Circuit",
        "Ark Stage 3/Depths",
      ],
    },
    {
      id: 15,
      title: "Spike Sweeper",
      isEnemy: true,
      locationText:
        "Found in Intro Stage/Central Station, Trace/Patch Circuit, Medley/Wave Circuit, Ark Stage 1/Entrance, Ark Stage 3/Depths",
      locations: [
        "Intro Stage/Central Station",
        "Trace/Patch Circuit",
        "Medley/Wave Circuit",
        "Ark Stage 1/Entrance",
        "Ark Stage 3/Depths",
      ],
    },
    {
      id: 16,
      title: "Elec Sweeper",
      isEnemy: true,
      locationText: "Found in Cable/Power Circuit, Ark Stage 1/Entrance",
      locations: ["Cable/Power Circuit", "Ark Stage 1/Entrance"],
    },
    {
      id: 17,
      title: "Heat Sweeper",
      isEnemy: true,
      locationText:
        "Found in Ray/Optic Circuit, Ark Stage 2/Machinery, Ark Stage 3/Depths",
      locations: [
        "Ray/Optic Circuit",
        "Ark Stage 2/Machinery",
        "Ark Stage 3/Depths",
      ],
    },
    {
      id: 18,
      title: "Junk Creeper",
      isEnemy: true,
      locationText: "Found in Trace/Patch Circuit",
      locations: ["Trace/Patch Circuit"],
    },
    {
      id: 19,
      title: "Elec Creeper",
      isEnemy: true,
      locationText: "Found in Cable/Power Circuit, Ark Stage 1/Entrance",
      locations: ["Cable/Power Circuit", "Ark Stage 1/Entrance"],
    },
    {
      id: 20,
      title: "Snow Diver",
      isEnemy: true,
      locationText: "Found in Blade/Cooler Circuit, Ark Stage 3/Depths",
      locations: ["Blade/Cooler Circuit", "Ark Stage 3/Depths"],
    },
    {
      id: 21,
      title: "Ice Chucker",
      isEnemy: true,
      locationText: "Found in Blade/Cooler Circuit",
      locations: ["Blade/Cooler Circuit"],
    },
    {
      id: 22,
      title: "Ice Floater",
      isEnemy: true,
      locationText: "Found in Blade/Cooler Circuit",
      locations: ["Blade/Cooler Circuit"],
    },
    {
      id: 23,
      title: "Gunner Floater",
      isEnemy: true,
      locationText:
        "Found in Intro Stage/Central Station, Medley/Wave Circuit, Bit/Shift Circuit, Ark Stage 3/Depths",
      locations: [
        "Intro Stage/Central Station",
        "Medley/Wave Circuit",
        "Bit/Shift Circuit",
        "Ark Stage 3/Depths",
      ],
    },
    {
      id: 24,
      title: "Coolant Dispenser",
      isEnemy: true,
      locationText: "Found in Blade/Cooler Circuit, Ark Stage 3/Depths",
      locations: ["Blade/Cooler Circuit", "Ark Stage 3/Depths"],
    },
    {
      id: 25,
      title: "Freeze Turret",
      isEnemy: true,
      locationText: "Found in Blade/Cooler Circuit",
      locations: ["Blade/Cooler Circuit"],
    },
    {
      id: 26,
      title: "Boom Turret",
      isEnemy: true,
      locationText: "Found in Medley/Wave Circuit",
      locations: ["Medley/Wave Circuit"],
    },
    {
      id: 27,
      title: "Elec Sparker",
      isEnemy: true,
      locationText: "Found in Cable/Power Circuit, Ark Stage 1/Entrance",
      locations: ["Cable/Power Circuit", "Ark Stage 1/Entrance"],
    },
    {
      id: 28,
      title: "Mass Sparker",
      isEnemy: true,
      locationText: "Found in Cable/Power Circuit, Ark Stage 1/Entrance",
      locations: ["Cable/Power Circuit", "Ark Stage 1/Entrance"],
    },
    {
      id: 29,
      title: "Missile Platform",
      isEnemy: true,
      locationText: "Found in Bit/Shift Circuit, Ark Stage 1/Entrance",
      locations: ["Bit/Shift Circuit", "Ark Stage 1/Entrance"],
    },
    {
      id: 30,
      title: "Float Rocketeer",
      isEnemy: true,
      locationText:
        "Found in Bit/Shift Circuit, Ark Stage 1/Entrance, Ark Stage 3/Depths",
      locations: [
        "Bit/Shift Circuit",
        "Ark Stage 1/Entrance",
        "Ark Stage 3/Depths",
      ],
    },
    {
      id: 31,
      title: "Spring Hopper",
      isEnemy: true,
      locationText: "Found in Medley/Wave Circuit",
      locations: ["Medley/Wave Circuit"],
    },
    {
      id: 32,
      title: "Spring Boomer",
      isEnemy: true,
      locationText: "Found in Medley/Wave Circuit, Ark Stage 3/Depths",
      locations: ["Medley/Wave Circuit", "Ark Stage 3/Depths"],
    },
    {
      id: 33,
      title: "Block Bonker",
      isEnemy: true,
      locationText: "Found in Medley/Wave Circuit, Ark Stage 3/Depths",
      locations: ["Medley/Wave Circuit", "Ark Stage 3/Depths"],
    },
    {
      id: 34,
      title: "Hover Shield",
      isEnemy: true,
      locationText: "Found in Trace/Patch Circuit, Ark Stage 2/Machinery",
      locations: ["Trace/Patch Circuit", "Ark Stage 2/Machinery"],
    },
    {
      id: 35,
      title: "Flip Panel Turret",
      isEnemy: true,
      locationText: "Found in Medley/Wave Circuit",
      locations: ["Medley/Wave Circuit"],
    },
    {
      id: 36,
      title: "Quake Hammer",
      isEnemy: true,
      locationText: "Found in Crash/Break Circuit, Ark Stage 3/Depths",
      locations: ["Crash/Break Circuit", "Ark Stage 3/Depths"],
    },
    {
      id: 37,
      title: "Crush Jumper",
      isEnemy: true,
      locationText:
        "Found in Crash/Break Circuit, Ark Stage 1/Entrance, Ark Stage 3/Depths",
      locations: [
        "Crash/Break Circuit",
        "Ark Stage 1/Entrance",
        "Ark Stage 3/Depths",
      ],
    },
    {
      id: 38,
      title: "Crystal Floater",
      isEnemy: true,
      locationText: "Found in Hash/Cipher Circuit",
      locations: ["Hash/Cipher Circuit"],
    },
    {
      id: 39,
      title: "Magma Mortar",
      isEnemy: true,
      locationText: "Found in Ray/Optic Circuit, Ark Stage 2/Machinery",
      locations: ["Ray/Optic Circuit", "Ark Stage 2/Machinery"],
    },
    {
      id: 40,
      title: "Energy Mortar",
      isEnemy: true,
      locationText: "Found in Hash/Cipher Circuit",
      locations: ["Hash/Cipher Circuit"],
    },
    {
      id: 41,
      title: "Omnishot Turret",
      isEnemy: true,
      locationText:
        "Found in Ray/Optic Circuit, Ark Stage 1/Entrance, Ark Stage 2/Machinery, Ark Stage 3/Depths",
      locations: [
        "Ray/Optic Circuit",
        "Ark Stage 1/Entrance",
        "Ark Stage 2/Machinery",
        "Ark Stage 3/Depths",
      ],
    },
    {
      id: 42,
      title: "Cannon Hopper",
      isEnemy: true,
      locationText:
        "Found in Hash/Cipher Circuit, Ark Stage 2/Machinery, Ark Stage 3/Depths",
      locations: [
        "Hash/Cipher Circuit",
        "Ark Stage 2/Machinery",
        "Ark Stage 3/Depths",
      ],
    },
    {
      id: 43,
      title: "Projectile Dispenser",
      isEnemy: true,
      locationText:
        "Found in Cable/Power Circuit, Hash/Cipher Circuit, Blade/Cooler Circuit, Crash/Break Circuit, Trace/Patch Circuit, Medley/Wave Circuit, Ray/Optic Circuit, Ark Stage 1/Entrance, Ark Stage 2/Machinery, Ark Stage 3/Depths",
      locations: [
        "Cable/Power Circuit",
        "Hash/Cipher Circuit",
        "Blade/Cooler Circuit",
        "Crash/Break Circuit",
        "Trace/Patch Circuit",
        "Medley/Wave Circuit",
        "Ray/Optic Circuit",
        "Ark Stage 1/Entrance",
        "Ark Stage 2/Machinery",
        "Ark Stage 3/Depths",
      ],
    },
    {
      id: 44,
      title: "Scrap Golem",
      isEnemy: true,
      locationText: "Found in Trace/Patch Circuit",
      locations: ["Trace/Patch Circuit"],
    },
    {
      id: 45,
      title: "V. Assault Heli",
      isEnemy: true,
      locationText: "Found in Bit/Shift Circuit",
      locations: ["Bit/Shift Circuit"],
    },
  ],
  characters: [
    {
      id: 1,
      title: "Kai",
      isEnemy: false,
      locationText:
        "Obtained in the transfer room after defeating the final boss.",
      locations: [],
    },
    {
      id: 2,
      title: "Nameless",
      isEnemy: false,
      locationText:
        "Obtained in the transfer room after defeating the final boss.",
      locations: [],
    },
    {
      id: 3,
      title: "Negative [their actual name gets censored by Steam]",
      isEnemy: false,
      locationText:
        "Found behind the glass tube in the Medbay, the tube blocks access to it and is only removed after rescuing all 64 citizens.",
      locations: [],
    },
    {
      id: 4,
      title: "Kernel",
      isEnemy: false,
      locationText:
        "Obtained in the transfer room after defeating all eight Rebel Circuits.",
      locations: [],
    },
    {
      id: 5,
      title: "Pat",
      isEnemy: false,
      locationText: "Obtained by talking to them.",
      locations: [],
    },
    {
      id: 6,
      title: "Delta",
      isEnemy: false,
      locationText: "Obtained by talking to them.",
      locations: [],
    },
    {
      id: 7,
      title: "Epsilon",
      isEnemy: false,
      locationText: "Obtained by talking to them.",
      locations: [],
    },
    {
      id: 8,
      title: "Zeta",
      isEnemy: false,
      locationText: "Obtained by talking to them.",
      locations: [],
    },
    {
      id: 9,
      title: "Medic",
      isEnemy: false,
      locationText: "Obtained by talking to them.",
      locations: [],
    },
    {
      id: 10,
      title: "Nurse",
      isEnemy: false,
      locationText: "Obtained by purchasing any chip.",
      locations: [],
    },
    {
      id: 11,
      title: "Alph",
      isEnemy: false,
      locationText: "Obtained by researching any collected data chip.",
      locations: [],
    },
    {
      id: 12,
      title: "Data",
      isEnemy: false,
      locationText:
        "Obtained by talking to them after having completed Ark Stage 2/Machinery.",
      locations: [],
    },
    {
      id: 13,
      title: "Amadeus",
      isEnemy: false,
      locationText:
        "Obtained by petting them (using the Burst button near them) for a few seconds.",
      locations: [],
    },
    {
      id: 14,
      title: "Yuki",
      isEnemy: false,
      locationText:
        "Obtained by petting them (using the Burst button near them) for a few seconds.",
      locations: [],
    },
    {
      id: 15,
      title: "Fix",
      isEnemy: false,
      locationText:
        "Obtained by relaxing with them (using the Burst button near them) for a few seconds.",
      locations: [],
    },
    {
      id: 16,
      title: "Shock",
      isEnemy: false,
      locationText: "Obtained by talking to them.",
      locations: [],
    },
    {
      id: 17,
      title: "Prim",
      isEnemy: false,
      locationText: "Obtained by talking to them.",
      locations: [],
    },
    {
      id: 18,
      title: "K.I.D",
      isEnemy: false,
      locationText:
        "Obtained by scoring a goal with the ball they spawn after talking to them twice.",
      locations: [],
    },
    {
      id: 19,
      title: "Mighty",
      isEnemy: false,
      locationText: "Obtained by talking to them.",
      locations: [],
    },
    {
      id: 20,
      title: "Tech",
      isEnemy: false,
      locationText: "Obtained by talking to them.",
      locations: [],
    },
    {
      id: 21,
      title: "Chronos",
      isEnemy: false,
      locationText: "Obtained by talking to them.",
      locations: [],
    },
    {
      id: 22,
      title: "Guardian Corps",
      isEnemy: false,
      locationText:
        "Obtained by entering the Guardian Corps HQ Vault after defeating any Rebel Circuit.",
      locations: [],
    },
  ],
  bosses: [
    {
      id: 1,
      title: "Ray",
      isEnemy: false,
      locationText: null,
      locations: [],
    },
    {
      id: 2,
      title: "Trace",
      isEnemy: false,
      locationText: null,
      locations: [],
    },
    {
      id: 3,
      title: "Blade",
      isEnemy: false,
      locationText: null,
      locations: [],
    },
    {
      id: 4,
      title: "Cable",
      isEnemy: false,
      locationText: null,
      locations: [],
    },
    {
      id: 5,
      title: "Bit",
      isEnemy: false,
      locationText: null,
      locations: [],
    },
    {
      id: 6,
      title: "Medley",
      isEnemy: false,
      locationText: null,
      locations: [],
    },
    {
      id: 7,
      title: "Crash",
      isEnemy: false,
      locationText: null,
      locations: [],
    },
    {
      id: 8,
      title: "Hash",
      isEnemy: false,
      locationText: null,
      locations: [],
    },
    {
      id: 9,
      title: "Negative [their actual name gets censored by Steam]",
      isEnemy: false,
      locationText: null,
      locations: [],
    },
    {
      id: 10,
      title: "Wrecker Tank",
      isEnemy: false,
      locationText: null,
      locations: [],
    },
    {
      id: 11,
      title: "Circuit Crystal",
      isEnemy: false,
      locationText: null,
      locations: [],
    },
    {
      id: 12,
      title: "Kernel",
      isEnemy: false,
      locationText: null,
      locations: [],
    },
    {
      id: 13,
      title: "Commander Circuit",
      isEnemy: false,
      locationText: null,
      locations: [],
    },
  ],
};

export const textures = {
  enemies: {
    "1": {
      x: 879,
      y: 243,
      width: 39,
      height: 33,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -2,
    },
    "2": {
      x: 737,
      y: 313,
      width: 52,
      height: 35,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -2,
    },
    "3": {
      x: 431,
      y: 234,
      width: 42,
      height: 33,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -6,
    },
    "4": {
      x: 969,
      y: 475,
      width: 49,
      height: 37,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -36,
    },
    "5": {
      x: 858,
      y: 597,
      width: 47,
      height: 38,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -33,
    },
    "6": {
      x: 627,
      y: 138,
      width: 27,
      height: 27,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -2,
    },
    "7": {
      x: 917,
      y: 113,
      width: 26,
      height: 26,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -7,
    },
    "8": {
      x: 946,
      y: 113,
      width: 27,
      height: 26,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -10,
    },
    "9": {
      x: 268,
      y: 132,
      width: 20,
      height: 27,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -14,
    },
    "10": {
      x: 128,
      y: 106,
      width: 32,
      height: 23,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -16,
    },
    "11": {
      x: 583,
      y: 2,
      width: 50,
      height: 16,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -1,
    },
    "12": {
      x: 701,
      y: 312,
      width: 33,
      height: 35,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -30,
    },
    "13": {
      x: 27,
      y: 105,
      width: 35,
      height: 22,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -14,
    },
    "29": {
      x: 635,
      y: 310,
      width: 36,
      height: 35,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -30,
    },
    "33": {
      x: 501,
      y: 110,
      width: 33,
      height: 24,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -25,
    },
    "26": {
      x: 932,
      y: 2,
      width: 28,
      height: 17,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -3,
    },
    "42": {
      x: 986,
      y: 174,
      width: 29,
      height: 31,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -9,
    },
    "37": {
      x: 624,
      y: 859,
      width: 50,
      height: 46,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -15,
    },
    "38": {
      x: 317,
      y: 542,
      width: 20,
      height: 39,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -6,
    },
    "27": {
      x: 200,
      y: 106,
      width: 28,
      height: 23,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -10,
    },
    "19": {
      x: 896,
      y: 21,
      width: 29,
      height: 18,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -1,
    },
    "16": {
      x: 636,
      y: 2,
      width: 22,
      height: 16,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -13,
    },
    "17": {
      x: 139,
      y: 2,
      width: 20,
      height: 14,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -14,
    },
    "35": {
      x: 33,
      y: 38,
      width: 16,
      height: 18,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -16,
    },
    "24": {
      x: 23,
      y: 2,
      width: 26,
      height: 13,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -20,
    },
    "25": {
      x: 829,
      y: 42,
      width: 30,
      height: 19,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -2,
    },
    "32": {
      x: 124,
      y: 161,
      width: 26,
      height: 29,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -27,
    },
    "34": {
      x: 351,
      y: 134,
      width: 32,
      height: 27,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -4,
    },
    "21": {
      x: 766,
      y: 111,
      width: 29,
      height: 25,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -34,
    },
    "22": {
      x: 408,
      y: 61,
      width: 34,
      height: 20,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -31,
    },
    "18": {
      x: 261,
      y: 39,
      width: 33,
      height: 18,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -14,
    },
    "28": {
      x: 89,
      y: 131,
      width: 32,
      height: 26,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -16,
    },
    "41": {
      x: 776,
      y: 86,
      width: 22,
      height: 22,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -9,
    },
    "39": {
      x: 607,
      y: 63,
      width: 32,
      height: 20,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -24,
    },
    "40": {
      x: 784,
      y: 63,
      width: 30,
      height: 20,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -25,
    },
    "36": {
      x: 963,
      y: 639,
      width: 29,
      height: 40,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -35,
    },
    "30": {
      x: 979,
      y: 777,
      width: 34,
      height: 44,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -31,
    },
    "44": {
      x: 279,
      y: 902,
      width: 72,
      height: 58,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -0,
    },
    "23": {
      x: 801,
      y: 87,
      width: 34,
      height: 22,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -31,
    },
    "20": {
      x: 953,
      y: 65,
      width: 22,
      height: 20,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -29,
    },
    "15": {
      x: 27,
      y: 59,
      width: 26,
      height: 19,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -11,
    },
    "31": {
      x: 901,
      y: 2,
      width: 28,
      height: 16,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -10,
    },
    "14": {
      x: 375,
      y: 20,
      width: 45,
      height: 17,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -10,
    },
    "45": {
      x: 428,
      y: 1170,
      width: 69,
      height: 80,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -68,
    },
    "43": {
      x: 132,
      y: 1014,
      width: 54,
      height: 64,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -13,
    },
  },
  bosses: {
    "5": {
      x: 33,
      y: 495,
      width: 38,
      height: 38,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -46,
    },
    "3": {
      x: 248,
      y: 756,
      width: 41,
      height: 44,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -48,
    },
    "4": {
      x: 112,
      y: 539,
      width: 35,
      height: 38,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -11,
    },
    "13": {
      x: 928,
      y: 1049,
      width: 68,
      height: 66,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -2,
    },
    "7": {
      x: 2,
      y: 893,
      width: 59,
      height: 48,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -31,
    },
    "11": {
      x: 500,
      y: 1176,
      width: 48,
      height: 86,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -32,
    },
    "2": {
      x: 135,
      y: 418,
      width: 28,
      height: 37,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -34,
    },
    "8": {
      x: 174,
      y: 666,
      width: 52,
      height: 41,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -17,
    },
    "12": {
      x: 136,
      y: 708,
      width: 32,
      height: 42,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -64,
    },
    "6": {
      x: 563,
      y: 716,
      width: 41,
      height: 42,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -9,
    },
    "9": {
      x: 76,
      y: 338,
      width: 32,
      height: 36,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -24,
    },
    "1": {
      x: 963,
      y: 435,
      width: 45,
      height: 37,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -15,
    },
    "10": {
      x: 671,
      y: 976,
      width: 70,
      height: 61,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -0,
    },
  },
  characters: {
    "13": {
      x: 2,
      y: 81,
      width: 28,
      height: 21,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -1,
    },
    "18": {
      x: 334,
      y: 164,
      width: 27,
      height: 30,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -6,
    },
    "15": {
      x: 595,
      y: 272,
      width: 36,
      height: 35,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -4,
    },
    "21": {
      x: 784,
      y: 354,
      width: 38,
      height: 36,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -7,
    },
    "5": {
      x: 223,
      y: 229,
      width: 29,
      height: 35,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -4,
    },
    "22": {
      x: 545,
      y: 761,
      width: 88,
      height: 44,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -7,
    },
    "1": {
      x: 403,
      y: 308,
      width: 38,
      height: 35,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -14,
    },
    "4": {
      x: 473,
      y: 759,
      width: 33,
      height: 44,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -2,
    },
    "11": {
      x: 197,
      y: 194,
      width: 26,
      height: 32,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -6,
    },
    "9": {
      x: 461,
      y: 425,
      width: 28,
      height: 37,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -1,
    },
    "19": {
      x: 834,
      y: 638,
      width: 40,
      height: 39,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -1,
    },
    "3": {
      x: 203,
      y: 304,
      width: 32,
      height: 35,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -32,
    },
    "20": {
      x: 905,
      y: 207,
      width: 25,
      height: 33,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -5,
    },
    "10": {
      x: 180,
      y: 381,
      width: 32,
      height: 36,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -1,
    },
    "17": {
      x: 301,
      y: 462,
      width: 41,
      height: 37,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -2,
    },
    "12": {
      x: 153,
      y: 227,
      width: 32,
      height: 33,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -4,
    },
    "6": {
      x: 299,
      y: 584,
      width: 38,
      height: 38,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -29,
    },
    "7": {
      x: 382,
      y: 385,
      width: 37,
      height: 36,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -34,
    },
    "8": {
      x: 722,
      y: 470,
      width: 34,
      height: 37,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -10,
    },
    "16": {
      x: 904,
      y: 173,
      width: 37,
      height: 31,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -5,
    },
    "2": {
      x: 535,
      y: 387,
      width: 36,
      height: 36,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -21,
    },
    "14": {
      x: 984,
      y: 142,
      width: 30,
      height: 29,
      textureWidth: 1024,
      textureHeight: 2048,
      offsetX: 0,
      offsetY: 1,
      originalWidth: 1,
      originalHeight: -2,
    },
  },
};
